RideServiceProviderClassName: 设计模式.工厂.抽象工厂.共享经济.service.ride.UberRide
FoodDeliveryServiceProviderClassName: 设计模式.工厂.抽象工厂.共享经济.service.eats.MeituanEats
GroceryDeliveryServiceProviderClassName: 设计模式.工厂.抽象工厂.共享经济.service.grocery.GrabFresh